name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: kki_db
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo_mysql, dom, xml, ctype, json
          tools: phpstan, composer, phpunit

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Set up TailwindCSS
        run: npm ci

      - name: Create .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Migrate database
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: kki_db
          DB_USERNAME: root
          DB_PASSWORD: ""
        run: php artisan migrate --force

      - name: Run PHPStan
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: kki_db
          DB_USERNAME: root
          DB_PASSWORD: ""
        run: vendor/bin/phpstan analyse --memory-limit=1G --error-format=github

      - name: Run PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: kki_db
          DB_USERNAME: root
          DB_PASSWORD: ""
        run: vendor/bin/phpunit
        
